export const NATIONALITY = {
    AU:'AU',
    BR:'BR',
    CA:'CA',
    CH:'CH',
    DE:'DE',
    DK:'DK',
    ES:'ES',
    FI:'FI',
    FR:'FR',
    GB:'GB',
    IE:'IE',
    IR:'IR',
    NO:'NO',
    NL:'NL',
    NZ:'NZ',
    TR:'TR',
    US:'US',
}

export const NATIONALITY_HUMAN_NAME = {
    [NATIONALITY.AU] : 'Australian',
    [NATIONALITY.BR] : "Brazilian",
    [NATIONALITY.CA] : 'Canadian',
    [NATIONALITY.CH] :  "Chinese",
    [NATIONALITY.DE] : 'German',
    [NATIONALITY.DK] : 'Danish',
    [NATIONALITY.ES] : 'Spanish',
    [NATIONALITY.FI] : 'Finnish',
    [NATIONALITY.FR] : 'French',
    [NATIONALITY.GB] : 'British',
    [NATIONALITY.IE] : 'Irish',
    [NATIONALITY.IR] : 'Iranian',
    [NATIONALITY.NO] : 'Norwegian',
    [NATIONALITY.NL] : 'Dutch',
    [NATIONALITY.NZ] : 'New Zeland',
    [NATIONALITY.TR] : 'Turkish',
    [NATIONALITY.US] : 'American'   
}

export const NATIONAL_COLOR = {
    AU: "#9F1B69",
    BR: "#E864B2",
    CA: "#4461EC",
    CH: "#51C453",
    DE:  "#33C5C9",
    DK: "#F98C39",
    ES:  "#FA7F56",
 
    FI: "#2B94FF",
    FR: "#9F1B69",
    GB: "#E864B2",
    IE: "#4461EC",
    IR: "#51C453",
    NO: "#33C5C9",   
    NL: "#F98C39",
    NZ: "#FA7F56",
    TR: "#2B94FF",
    US:  "#9F1B69",
  };